services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - '${FASTAPI_PORT}:${FASTAPI_PORT}'
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${PROJECT_TITLE}-db:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'

volumes:
  rarity-api-db:
    name: ${PROJECT_TITLE}-db
